### ISSUE TITLE
Magento 2.1 Interceptors & Type Hinting

### ISSUE THREAD

**Issue by Serializator** [yireo/Yireo_CheckoutTester2#15]
In Magento 2.1 there was a bug that when type hinting was used, an incompatibility error would be thrown on generated interceptors.

`Yireo\CheckoutTester2\Block\Field` has these type hints which causes Yireo CheckoutTester2 to throw an incompatibility error when accessing the configuration section for Yireo CheckoutTester2.

I'm not entirely sure whether this is because of developer mode, one of the Magento instances on production mode seems to be fine when accessing the Yireo CheckoutTester2 configuration section, same exact Magento version.

[M2.1.2 : Interceptor breaks when type hinting a string](https://github.com/magento/magento2/issues/7620)

**Comment by jissereitsma** [comment]
I found this an interesting issue nonetheless. ;) Why did you close it?

**Comment by Serializator** [comment]
I closed it because I thought it was more of a problem with my local environment than a product issue.
I reopened it because it might be worth looking into, I'll also try to find a reproducible case to make sure it isn't specific to my environment.

**Comment by jissereitsma** [comment]
I'm closing this anyway now. I never go this reproduced under 2.2 and 2.3 and it might have been a bug within the used Magento environment. Thanks for reporting anyway!
