### ISSUE TITLE
Composer installation instructions incorrect

### ISSUE THREAD

**Issue by hostep** [yireo/Yireo_CheckoutTester2#2]
```
$ composer config repositories.yireo-free composer https://satis.yireo.com
$ composer require yireo/yireo_checkouttester2

  [InvalidArgumentException]
  Could not find package yireo/yireo_checkouttester2 at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability
```

Well, the instructions are probably correct, but this module doesn't exist at https://satis.yireo.com/, so that is most likely the real problem :)

**Comment by jissereitsma** [comment]
That kind of makes sense. It is fixed now - the CheckoutTester2 extension is also added to our Satis. Another note is that we most likely will add all our composer-based extensions on Packagist anyway, exploding the big package mess even more, but with the benefit that our own Satis is not needed anymore.
