### ISSUE TITLE
failed to open stream: No such file or directory in

### ISSUE THREAD

**Issue by DependencyHell** [yireo/Yireo_CheckoutTester2#3]
Hi, 

and thanks for this useful module, I just have a problem with Magento 2.1.6 :

I'm installing magento 2 with composer and CheckoutTester is set in `require-dev` section : 
`"yireo/yireo_checkouttester2": "^0.0.2"` 

Everything works fine, but then, I'm running :
`php bin/magento sampledata:deploy`

and it shows :

> [Exception]                                                                                                                                                                       
>   Warning: file_get_contents(/var/www/myproject/magento2/vendor/yireo/yireo_checkouttester2/source/composer.json): failed to open stream: No such file or directory in /var/www/myproject/magento2/vendor/magento/module-sample-data/Model/Dependency.php on line 109                                                               
>                                                                                                                                                                                     
> 
> sampledata:deploy

There is this problem that seems related : 
https://mage2.pro/t/topic/327
https://github.com/magento/magento2/issues/4636

So, I have two questions, it seems that Magento 2 forces to have a composer.json in the module folder, but yours have one, just setup in parent folder. And why your module is in a source folder and not in the main folder?

Thanks

**Comment by jissereitsma** [comment]
With some of the later versions of Magento 2, there has come up the mysterious requirement to have all of the module files living in the same folder as the `composer.json` file, while we had a personal approach that module files were always in a subfolder `source` (which is actually standard in a lot of other different open source projects as a means not to mix source files with installer files). Regardless of how stupid I consider this to be, this is now a Magento 2 requirement. We fixed this for many modules, but not yet for the CheckoutTester. This is now fixed and it should not work properly.
