### ISSUE TITLE
Source folder is missing in 0.0.3

### ISSUE THREAD

**Issue by thijsvandberg** [yireo/Yireo_CheckoutTester2#4]
Hi,

I think you accidentally removed the source folder.

**Comment by yireo** [comment]
Actually, having a `source` folder (as I used to do throughout all our projects) is deprecated in Magento 2.1. While compiling code, there are checks that the `composer.json` lives on the same level as all other files (that used to be in `source`). So in fact, the `source` folder has been removed on purpose to be compliant to M2.1. Doesn't this work?

**Comment by yireo** [comment]
I guess not. Version 0.0.3 was indeed missing the source folder, most likely due to running a new release without pushing changes first. This is now fixed in 0.0.4.

**Comment by thijsvandberg** [comment]
Thx! Could you update your package on Packagist? You could also setup Packagist to auto-update after each commit via a webhook.
