### ISSUE TITLE
Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given 

### ISSUE THREAD

**Issue by EliasKotlyar** [yireo/Yireo_CheckoutTester2#6]
This errors happens, if you dont have inserted anything in the "IP-Field":

( ! )  Fatal error: Uncaught TypeError: trim() expects parameter 1 to be  string, null given in  /var/www/***/magento/vendor/yireo/magento2-checkouttester2/Helper/Data.php  on line 53
--

If you insert " " (space) , everything will work as expected.

Greetings
Elias

**Comment by yireo** [comment]
The space comment got me on the wrong foot, but the PR explains all. Many thanks for giving feedback on this. PR will be merged right away and I'll run a new release.
