### ISSUE TITLE
Backend link to success page fails

### ISSUE THREAD

**Issue by rikwillems** [yireo/Yireo_CheckoutTester2#8]
When you click the backend link (on settings page) to the success page it gives a 404. It opens in the admin url space, not the frontend.

**Comment by jissereitsma** [comment]
I can't confirm this issue. Which version have you installed on which version of Magento 2? I've tested this under Magento 2.2.2 with module version 0.0.6 ...

**Comment by rikwillems** [comment]
Hi Jisse sorry for the inconvenience. The version got stuck at 0.0.2 due to my composer.json restraint. After fixing this the module updated and now the link is correct. Thanks!
